version: '3'
  
services:  
    swingSTR:
        container_name: swingSTR
        image: php:apache
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
        restart: unless-stopped
