version: '3'
  
services:
    swingSTR:
        container_name: swingSTR
        image: php:apache
        expose:
            - 80
        volumes:
            - ./html:/var/www/html
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: swingstr.de
            LETSENCRYPT_HOST: swingstr.de

networks:
  default:
    external:
      name: nginx-proxy